name-template: 'Release ${{ nextReleaseVersion }} ğŸš€'
tag-template: 'v${{ nextReleaseVersion }}'
categories:
  - title: 'ğŸš€ Features'
    labels:
      - 'feature'
  - title: 'ğŸ› Bug Fixes'
    labels:
      - 'bug'
  - title: 'ğŸ› ï¸ Maintenance'
    labels:
      - 'chore'
      - 'refactor'
  - title: 'ğŸ§© Dependencies'
    labels:
      - 'dependencies'
change-template: '- $TITLE by @$AUTHOR in #$NUMBER'
template: |
  ## What's Changed
  $CHANGES

  ## ğŸ“¦ Full Changelog
  [Compare Changes](https://github.com/${{ github.repository }}/compare/${{ previousTag }}...${{ currentTag }})
